#!/usr/bin/env ansible-playbook
---
- name: ACTIVEMQ STARTUP
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    # Environment variables
    activemq_username: "{{lookup('env','ACTIVEMQ_USERNAME')|default('system',true)}}"
    activemq_password: "{{lookup('env','ACTIVEMQ_PASSWORD')|default('manager',true)}}"
    postgres_enabled: "{{lookup('env','POSTGRES_ENABLED')|default(false,true)}}"
    postgres_host: "{{lookup('env','POSTGRES_HOST')|default('postgres',true)}}"
    postgres_port: "{{lookup('env','POSTGRES_PORT')|default(5432,true)}}"
    postgres_database: "{{lookup('env','POSTGRES_DATABASE')|default('postgres',true)}}"
    postgres_username: "{{lookup('env','POSTGRES_USERNAME')|default('postgres',true)}}"
    postgres_password: "{{lookup('env','POSTGRES_PASSWORD')|default('postgres',true)}}"
    postgres_init: "{{lookup('env','POSTGRES_INIT')|default(false,true)}}"
    postgres_conn_init: "{{lookup('env','POSTGRES_CONN_INIT')|default(2,true)}}"
    postgres_conn_idle: "{{lookup('env','POSTGRES_CONN_IDLE')|default(4,true)}}"
    postgres_conn_max: "{{lookup('env','POSTGRES_CONN_MAX')|default(10,true)}}"
    hawtio_enabled: "{{lookup('env','HAWTIO_ENABLED')|default(false,true)}}"
    log4j_loglevel: "{{lookup('env','LOG4J_LOGLEVEL')|default('INFO',true)}}"
    log4j_logfile: "{{lookup('env','LOG4J_LOGFILE')|default('/tmp/activemq.log',true)}}"
    auth_enabled: "{{lookup('env','AUTH_ENABLED')|default(true,true)}}"
    openwire_enabled: "{{lookup('env','OPENWIRE_ENABLED')|default(true,true)}}"
    openwire_maxinactivity: "{{lookup('env','OPENWIRE_MAXINACTIVITY')|default(0,true)}}"
    openwire_maxconn: "{{lookup('env','OPENWIRE_MAXCONN')|default(1000,true)}}"
    openwire_maxframesize: "{{lookup('env','OPENWIRE_MAXFRAMESIZE')|default(1048576000,true)}}"
    stomp_enabled: "{{lookup('env','STOMP_ENABLED')|default(false,true)}}"
    ampq_enabled: "{{lookup('env','AMPQ_ENABLED')|default(false,true)}}"
    mqtt_enabled: "{{lookup('env','MQTT_ENABLED')|default(false,true)}}"
    ws_enabled: "{{lookup('env','WS_ENABLED')|default(false,true)}}"

  tasks:
  - name: RENDER ENVIRONMENT FILE
    ansible.builtin.template:
      src: "./templates/{{item.name}}.j2"
      dest: /opt/activemq/bin/env
      owner: activemq
      group: activemq
      mode: '0640'
      force: true
    loop:
    - name: activemq.env
    #loop_control:
    #  label: "{{ item.name }}"

  - name: RENDER CONFIG FILES
    ansible.builtin.template:
      src: "./templates/{{item.name}}.j2"
      dest: "/opt/activemq/conf/{{item.name}}"
      owner: activemq
      group: activemq
      mode: '0640'
      force: true
    loop:
    - name: activemq.xml
    - name: jetty.xml
    - name: login.config
    - name: credentials.properties
    - name: users.properties
    - name: groups.properties
    - name: db.properties
    - name: jetty-realm.properties
    - name: logging.properties
    - name: log4j.properties
...
# Ansible Modules used in this playbook:
# - https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html