---
name: Build (Docker)

on:
  workflow_dispatch:

  schedule:
  - cron: '30 0 15 * *' # https://crontab.guru/

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_GITHUB_IMAGE: ${{ github.repository }}
  REGISTRY_DOCKERHUB: registry.hub.docker.com
  REGISTRY_DOCKERHUB_IMAGE: kdsda/nomad-pack

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: true
      matrix:
        java_version:
        - '11'
        activemq_version:
        - '5.16.3'
        - '5.15.15'

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Get date
      id: timestamp
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=week::$(date +'%Y.%V')"
    -
      name: Login to GitHub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Login to Docker Hub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_DOCKERHUB }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: |
          ${{ env.REGISTRY_GITHUB }}/${{ env.REGISTRY_GITHUB_IMAGE }}
          ${{ env.REGISTRY_DOCKERHUB }}/${{ env.REGISTRY_DOCKERHUB_IMAGE }}
        flavor: |
          latest=auto
          prefix=${{ matrix.java_version }}-,onlatest=true
        tags: |
          type=raw,value=${{ matrix.activemq_version }}-${{ steps.timestamp.outputs.week }}
          type=raw,value=${{ matrix.activemq_version }}
        labels: |
          org.opencontainers.image.title='activemq'
          org.opencontainers.image.description='ActiveMQ (Classic)'
          org.opencontainers.image.version="{{ matrix.activemq_version }}"
          org.opencontainers.image.vendor='Kreditorforeningen'
          org.opencontainers.image.authors='drift@kred.no'
          org.opencontainers.image.source='https://github.com/Kreditorforeningens-Driftssentral-DA/container-image-activemq'
          org.opencontainers.image.created="${{ steps.timestamp.outputs.date }}"
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        file: "docker/Dockerfile.public"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          IMAGE_NAME=azul/zulu-openjdk-debian
          IMAGE_TAG=${{ matrix.java_version }}
          ACTIVEMQ_VERSION=${{ matrix.activemq_version }}
          HAWTIO_VERSION=2.14.4
          JDBC_VERSION=42.3.1
