# NOTE - Docker Hub not in use; images are different
---
name: Build (Docker)

on:
  workflow_dispatch:

  schedule:
  - cron: '30 0 15 * *' # https://crontab.guru/

env:
  REGISTRY_GITHUB: ghcr.io
  REGISTRY_GITHUB_IMAGE: ${{ github.repository }}
  #REGISTRY_DOCKERHUB: registry.hub.docker.com
  #REGISTRY_DOCKERHUB_IMAGE: kdsda/activemq

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write
      contents: read

    strategy:
      fail-fast: true
      matrix:
        image_build: ["debian:stable"]
        image_runtime: ["azul/zulu-openjdk-debian:11"]
        activemq_version:
        - '5.17.1'
        - '5.16.5'
        hawtio_version: ["2.15.0"]
        jdbc_version: ["42.4.1"]

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Get date
      id: timestamp
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=week::$(date +'%Y.%V')"
    -
      name: Login to GitHub registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY_GITHUB }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    #-
    #  name: Login to Docker Hub registry
    #  uses: docker/login-action@v1 
    #  with:
    #    registry: ${{ env.REGISTRY_DOCKERHUB }}
    #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #    password: ${{ secrets.DOCKER_HUB_SECRET }}
    -
      name: Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY_GITHUB }}/${{ env.REGISTRY_GITHUB_IMAGE }}
        tags: |
          type=raw,value=${{ matrix.activemq_version }}-${{ steps.timestamp.outputs.week }}
          type=raw,value=${{ matrix.activemq_version }}
        labels: |
          org.opencontainers.image.title='activemq'
          org.opencontainers.image.description='ActiveMQ (Classic)'
          org.opencontainers.image.version={{ matrix.activemq_version }}
          org.opencontainers.image.vendor='Kreditorforeningen'
          org.opencontainers.image.authors='drift@kred.no'
          org.opencontainers.image.source='https://github.com/Kreditorforeningens-Driftssentral-DA/container-image-activemq'
          org.opencontainers.image.created=${{ steps.timestamp.outputs.date }}
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker
        file: "docker/Dockerfile.public"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          image_build=${{ matrix.image_build }}
          image_runtime=${{ matrix.image_runtime }}
          activemq_version=${{ matrix.activemq_version }}
          hawtio_version=${{ matrix.hawtio_version }}
          jdbc_version=${{ matrix.jdbc_version }}
