# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
---
name: Packer Public

on: [workflow_dispatch]

jobs:
  ubuntu-2004:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        TARGET_PREPARE: prepare.docker.UBUNTU_2004
        TARGET_PROVISION: provision.docker.UBUNTU_PREPARED
        PKR_VAR_docker_image_name: "registry.hub.docker.com/kdsda/activemq"
        PKR_VAR_docker_image_tag: "0.2.0"
        PKR_VAR_docker_login_server: "registry.hub.docker.com"
        PKR_VAR_docker_login_username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        PKR_VAR_docker_login_password: "${{ secrets.DOCKER_HUB_SECRET }}"
        PKR_VAR_activemq_version: '5.16.1'
        PKR_VAR_hawtio_version: '2.13.0'
        PKR_VAR_jdbc_postgres_version: '42.2.19'
      run: |
        # [ACTIVEMQ] BUILD & PUSH TO DOCKER HUB
        packer version
        docker --version
        ansible --version | head -n 1
        pushd src/packer
        packer fmt -diff -write=false .
        packer validate -only=${TARGET_PREPARE} .
        packer validate -only=${TARGET_PROVISION} .
        packer build -only=${TARGET_PREPARE} .
        packer build -only=${TARGET_PROVISION} .
        popd
...