# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# TODO: Create scheduled weekly builds (updating prepare/base image)
---
name: Packer Public (Docker Hub)

on: [workflow_dispatch]

jobs:
  
  alpine:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      env:
        PKR_VAR_java_version: openjdk11-jre-headless
        PKR_VAR_activemq_version: '5.16.3'
        PKR_VAR_hawtio_version: '2.14.0'
        PKR_VAR_jdbc_postgres_version: '42.2.24'
        PKR_VAR_registry_name: "registry.hub.docker.com/kdsda/activemq"
        PKR_VAR_registry_tags: "[\"latest\",\"alpine\",\"5.16.3\"]"
        PKR_VAR_registry_server: "registry.hub.docker.com"
        PKR_VAR_registry_username: "${{ secrets.DOCKER_HUB_USERNAME }}"
        PKR_VAR_registry_password: "${{ secrets.DOCKER_HUB_SECRET }}"
      run: |
        # BUILD & PUSH TO REGISTRY
        packer fmt -diff -write=false ./packer
        packer validate ./packer
        packer build ./packer
...
